package br.edu.qi.planetoffice.model;
// Generated 09/12/2018 19:07:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Deficiencia generated by hbm2java
 */
@Entity
@Table(name = "deficiencia")
public class Deficiencia implements java.io.Serializable {

	
	private Integer idDeficiencia;

	private String descricao;
	private Integer grau;
	private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

	public Deficiencia() {
	}

	public Deficiencia(String descricao, Integer grau) {
		this.descricao = descricao;
		this.grau = grau;
		this.idDeficiencia = null;
	}

	public Deficiencia(String descricao, Integer grau, Set<Pessoa> pessoas) {
		this.descricao = descricao;
		this.grau = grau;
		this.pessoas = pessoas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDeficiencia", unique = true, nullable = false)
	public Integer getIdDeficiencia() {
		return this.idDeficiencia;
	}

	public void setIdDeficiencia(Integer idDeficiencia) {
		this.idDeficiencia = idDeficiencia;
	}

	@Column(name = "descricao", length = 15)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "grau")
	public Integer getGrau() {
		return this.grau;
	}

	public void setGrau(Integer grau) {
		this.grau = grau;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "deficiencias")
	public Set<Pessoa> getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(Set<Pessoa> pessoas) {
		this.pessoas = pessoas;
	}

}
