package br.edu.qi.planetoffice.model;
// Generated 09/12/2018 19:07:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dia generated by hbm2java
 */
@Entity
@Table(name="dia")
public class Dia  implements java.io.Serializable {


     private Integer idDia;
     private String descricao;
     private Set<Horario> horarios = new HashSet<Horario>(0);

    public Dia() {
    }

    public Dia(String descricao, Set<Horario> horarios) {
       this.descricao = descricao;
       this.horarios = horarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDia", unique=true, nullable=false)
    public Integer getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(Integer idDia) {
        this.idDia = idDia;
    }

    
    @Column(name="descricao", length=70)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dia")
    public Set<Horario> getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }




}


