package br.edu.qi.planetoffice.model;
// Generated 09/12/2018 19:07:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="horario")
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private Dia dia;
     private String descricao;
     private Set<Turma> turmas = new HashSet<Turma>(0);
     private Set<HorarioPessoa> horarioPessoas = new HashSet<HorarioPessoa>(0);

    public Horario() {
    }

    public Horario(Dia dia, String descricao, Set<Turma> turmas, Set<HorarioPessoa> horarioPessoas) {
       this.dia = dia;
       this.descricao = descricao;
       this.turmas = turmas;
       this.horarioPessoas = horarioPessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHorario", unique=true, nullable=false)
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDia")
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }

    
    @Column(name="descricao", length=15)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="horario_turma", catalog="dbinterdisciplinar", joinColumns = { 
        @JoinColumn(name="idHorario", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idTurma", nullable=false, updatable=false) })
    public Set<Turma> getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set<Turma> turmas) {
        this.turmas = turmas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horario")
    public Set<HorarioPessoa> getHorarioPessoas() {
        return this.horarioPessoas;
    }
    
    public void setHorarioPessoas(Set<HorarioPessoa> horarioPessoas) {
        this.horarioPessoas = horarioPessoas;
    }




}


