package br.edu.qi.planetoffice.model;
// Generated 09/12/2018 19:07:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa")
public class Pessoa implements java.io.Serializable {

	private Integer idPessoa;
	private Etnia etnia;
	private Religiao religiao;
	private Sexo sexo;
	private Integer cep;
	private String logradouro;
	private String nomeSocial;
	private String nome;
	private Set<Deficiencia> deficiencias = new HashSet<Deficiencia>(0);
	private Aluno aluno;
	private Set<Telefone> telefones = new HashSet<Telefone>(0);
	private Set<Filiacao> filiacaos = new HashSet<Filiacao>(0);
	private Set<HorarioPessoa> horarioPessoas = new HashSet<HorarioPessoa>(0);
	private Professor professor;
	private Set<Venda> vendas = new HashSet<Venda>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Funcionario funcionario;

	public Pessoa() {
	}
	
	

	public Pessoa(Etnia etnia, Religiao religiao, Sexo sexo, Integer cep, String logradouro, String nomeSocial,
			String nome, Set<Deficiencia> deficiencias, Aluno aluno, Set<Telefone> telefones, Set<Filiacao> filiacaos,
			Set<HorarioPessoa> horarioPessoas, Professor professor, Set<Venda> vendas, Set<Usuario> usuarios,
			Funcionario funcionario) {
		this.etnia = etnia;
		this.religiao = religiao;
		this.sexo = sexo;
		this.cep = cep;
		this.logradouro = logradouro;
		this.nomeSocial = nomeSocial;
		this.nome = nome;
		this.deficiencias = deficiencias;
		this.aluno = aluno;
		this.telefones = telefones;
		this.filiacaos = filiacaos;
		this.horarioPessoas = horarioPessoas;
		this.professor = professor;
		this.vendas = vendas;
		this.usuarios = usuarios;
		this.funcionario = funcionario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPessoa", unique = true, nullable = false)
	public Integer getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtnia")
	public Etnia getEtnia() {
		return this.etnia;
	}

	public void setEtnia(Etnia etnia) {
		this.etnia = etnia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idReligiao")
	public Religiao getReligiao() {
		return this.religiao;
	}

	public void setReligiao(Religiao religiao) {
		this.religiao = religiao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSexo")
	public Sexo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	@Column(name = "cep")
	public Integer getCep() {
		return this.cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	@Column(name = "logradouro", length = 70)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "nome_social", length = 50)
	public String getNomeSocial() {
		return this.nomeSocial;
	}

	public void setNomeSocial(String nomeSocial) {
		this.nomeSocial = nomeSocial;
	}

	@Column(name = "nome", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "defic_pessoa", catalog = "dbinterdisciplinar", joinColumns = {
			@JoinColumn(name = "idPessoa", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idDeficiencia", nullable = false, updatable = false) })
	public Set<Deficiencia> getDeficiencias() {
		return this.deficiencias;
	}

	public void setDeficiencias(Set<Deficiencia> deficiencias) {
		this.deficiencias = deficiencias;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Aluno getAluno() {
		return this.aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<Telefone> getTelefones() {
		return this.telefones;
	}

	public void setTelefones(Set<Telefone> telefones) {
		this.telefones = telefones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<Filiacao> getFiliacaos() {
		return this.filiacaos;
	}

	public void setFiliacaos(Set<Filiacao> filiacaos) {
		this.filiacaos = filiacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<HorarioPessoa> getHorarioPessoas() {
		return this.horarioPessoas;
	}

	public void setHorarioPessoas(Set<HorarioPessoa> horarioPessoas) {
		this.horarioPessoas = horarioPessoas;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<Venda> getVendas() {
		return this.vendas;
	}

	public void setVendas(Set<Venda> vendas) {
		this.vendas = vendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

}
