package br.edu.qi.planetoffice.model;
// Generated 09/12/2018 19:07:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Religiao generated by hbm2java
 */
@Entity
@Table(name="religiao")
public class Religiao  implements java.io.Serializable {


     private Integer idReligiao;
     private String descricao;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Religiao() {
    }

    public Religiao(String descricao, Set<Pessoa> pessoas) {
       this.descricao = descricao;
       this.pessoas = pessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReligiao", unique=true, nullable=false)
    public Integer getIdReligiao() {
        return this.idReligiao;
    }
    
    public void setIdReligiao(Integer idReligiao) {
        this.idReligiao = idReligiao;
    }

    
    @Column(name="descricao", length=15)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="religiao")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


