package br.edu.qi.planetoffice.model;
// Generated 09/12/2018 19:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name="venda")
public class Venda  implements java.io.Serializable {


     private Integer idVenda;
     private Pessoa pessoa;
     private Date data;
     private Float valorTotal;
     private Set<ItemVenda> itemVendas = new HashSet<ItemVenda>(0);

    public Venda() {
    }

    public Venda(Pessoa pessoa, Date data, Float valorTotal, Set<ItemVenda> itemVendas) {
       this.pessoa = pessoa;
       this.data = data;
       this.valorTotal = valorTotal;
       this.itemVendas = itemVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVenda", unique=true, nullable=false)
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPessoa")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data", length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="valor_total", precision=12, scale=0)
    public Float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Float valorTotal) {
        this.valorTotal = valorTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="venda")
    public Set<ItemVenda> getItemVendas() {
        return this.itemVendas;
    }
    
    public void setItemVendas(Set<ItemVenda> itemVendas) {
        this.itemVendas = itemVendas;
    }




}


